config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  get 'examen', to: 'examen#index'
  get 'examen/:codigo', to: 'examen#show', as: 'examen_codigo'
  root to: 'home#inicio', as: 'inicio'
  resources :preguntas
  resources :evaluaciones

  devise_for :users     #metodos API REST para la APP de pasajes

	scope 'api' do
	  scope 'v1' do
  		resources :respuestas
  		#resources :empresas
  		#resources :imagenes
  		resources :roles
	  end
	end
end

app/controllers/evaluaciones_controller.rb
class EvaluacionesController < ActionController::Base
  layout "index"
  before_action :set_evaluacion, only: [:show, :edit, :update, :destroy]


  # GET /evaluaciones
  def index
    @evaluaciones = Evaluacion.all
  end

  # GET /evaluaciones/1
  def show
  end

  # GET /evaluaciones/new
  def new
    @evaluacion = Evaluacion.new
  end

  # GET /evaluaciones/1/edit
  def edit
  end

  # POST /evaluaciones
  def create
    @evaluacion = Evaluacion.new(evaluacion_params)

    if @evaluacion.save
      redirect_to @evaluacion, notice: 'Evaluacion was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /evaluaciones/1
  def update
    if @evaluacion.update(evaluacion_params)
      redirect_to @evaluacion, notice: 'Evaluacion was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /evaluaciones/1
  def destroy
    @evaluacion.destroy
    redirect_to evaluaciones_url, notice: 'Evaluacion was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evaluacion
      @evaluacion = Evaluacion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def evaluacion_params
      params.require(:evaluacion).permit(:nombre, :preguntas, :estado)
    end
end

app/helpers/evaluaciones_helper.rb
module EvaluacionesHelper
end

app/views/evaluaciones/_form.html.erb
<%= form_with(model: evaluacion) do |form| %>
  <% if evaluacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(evaluacion.errors.count, "error") %> prohibited this evaluacion from being saved:</h2>

      <ul>
        <% evaluacion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :preguntas %>
    <%#= form.number_field :preguntas %>
    <%= form.select :preguntas, ['1', '2', '3', '4', '5'] %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.select :estado, ['activo', 'desactivo'] %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/evaluaciones/edit.html.erb
<h1>Editing Evaluacion</h1>

<%= render 'form', evaluacion: @evaluacion %>

<%= link_to 'Show', @evaluacion %> |
<%= link_to 'Back', evaluaciones_path %>

app/views/evaluaciones/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Inicio', inicio_path %>
<h1>Evaluaciones</h1>

<table class="table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Nombre</th>
      <th>Preguntas</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @evaluaciones.each do |evaluacion| %>
      <tr>
        <td><%= evaluacion.id %></td>
        <td><%= evaluacion.nombre %></td>
        <td><%= evaluacion.preguntas %></td>
        <td><%= evaluacion.estado %></td>
        <td><%= link_to 'Show', evaluacion %></td>
        <td><%= link_to 'Edit', edit_evaluacion_path(evaluacion) %></td>
        <td><%= link_to 'Destroy', evaluacion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evaluacion', new_evaluacion_path %>

app/views/evaluaciones/new.html.erb
<h1>New Evaluacion</h1>

<%= render 'form', evaluacion: @evaluacion %>

<%= link_to 'Back', evaluaciones_path %>

app/views/evaluaciones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @evaluacion.nombre %>
</p>

<p>
  <strong>Preguntas:</strong>
  <%= @evaluacion.preguntas %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @evaluacion.estado %>
</p>

<%= link_to 'Edit', edit_evaluacion_path(@evaluacion) %> |
<%= link_to 'Back', evaluaciones_path %>