config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  get 'examen', to: 'examen#index'
  get 'examen/:codigo', to: 'examen#show', as: 'examen_codigo'
  root to: 'home#inicio', as: 'inicio'
  resources :preguntas
  resources :evaluaciones

  devise_for :users     #metodos API REST para la APP de pasajes

	scope 'api' do
	  scope 'v1' do
  		resources :respuestas
  		#resources :empresas
  		#resources :imagenes
  		resources :roles
	  end
	end
end

app/models/pregunta.rb
# == Schema Information
#
# Table name: preguntas
#
#  id            :integer          not null, primary key
#  evaluacion_id :integer          not null
#  texto         :string
#  correcta      :string
#  estado        :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class Pregunta < ApplicationRecord
  belongs_to :evaluacion

  validates :texto, :evaluacion, :correcta, presence: true

  before_create :create_record, :update_response

  before_update :update_response


  private
  def create_record
    self.estado = "activo"
  end

  def update_response
    if self.correcta == "Si" 
      Pregunta.where(:evaluacion_id => self.evaluacion_id).update_all("correcta = 'No'")
      self.correcta = "Si"
    end
  end

end

app/controllers/preguntas_controller.rb
class PreguntasController < ActionController::Base
  layout "index"
  
  before_action :set_pregunta, only: [:show, :edit, :update, :destroy]

  # GET /preguntas
  def index
    @preguntas = Pregunta.all
  end

  # GET /preguntas/1
  def show
  end

  # GET /preguntas/new
  def new
    @pregunta = Pregunta.new
  end

  # GET /preguntas/1/edit
  def edit
  end

  # POST /preguntas
  def create
    @pregunta = Pregunta.new(pregunta_params)

    if @pregunta.save
      redirect_to @pregunta, notice: 'Pregunta was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /preguntas/1
  def update
    if @pregunta.update(pregunta_params)
      redirect_to @pregunta, notice: 'Pregunta was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /preguntas/1
  def destroy
    @pregunta.destroy
    redirect_to preguntas_url, notice: 'Pregunta was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pregunta
      @pregunta = Pregunta.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pregunta_params
      params.require(:pregunta).permit(:evaluacion_id, :texto, :correcta, :estado)
    end
end

app/helpers/preguntas_helper.rb
module PreguntasHelper
end

app/views/preguntas/_form.html.erb
<%= form_with(model: pregunta) do |form| %>
  <% if pregunta.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pregunta.errors.count, "error") %> prohibited this pregunta from being saved:</h2>

      <ul>
        <% pregunta.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :evaluacion_id %>
    <%= form.select :evaluacion_id, options_for_select(Evaluacion.all.collect { | e | [e.nombre, e.id] }) %>
  </div>

  <div class="field">
    <%= form.label :texto %>
    <%= form.text_field :texto %>
  </div>

  <div class="field">
    <%= form.label :correcta %>
    <%= form.select :correcta, ['No', 'Si'] %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.select :estado, ['activo', 'desactivo'] %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/preguntas/edit.html.erb
<h1>Editing Pregunta</h1>

<%= render 'form', pregunta: @pregunta %>

<%= link_to 'Show', @pregunta %> |
<%= link_to 'Back', preguntas_path %>

app/views/preguntas/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Inicio', inicio_path %>
<h1>Preguntas</h1>

<table class="table">
  <thead>
    <tr>
      <th>Evaluacion</th>
      <th>Texto</th>
      <th>Correcta</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @preguntas.each do |pregunta| %>
      <tr>
        <td><%= Evaluacion.find(pregunta.evaluacion_id).nombre %></td>

        <td><%= pregunta.texto %></td>
        <td><%= pregunta.correcta %></td>
        <td><%= pregunta.estado %></td>
        <td><%= link_to 'Show', pregunta %></td>
        <td><%= link_to 'Edit', edit_pregunta_path(pregunta) %></td>
        <td><%= link_to 'Destroy', pregunta, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pregunta', new_pregunta_path %>

app/views/preguntas/new.html.erb
<h1>New Pregunta</h1>

<%= render 'form', pregunta: @pregunta %>

<%= link_to 'Back', preguntas_path %>

app/views/preguntas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Evaluacion:</strong>
  <%= @pregunta.evaluacion_id %>
</p>

<p>
  <strong>Texto:</strong>
  <%= @pregunta.texto %>
</p>

<p>
  <strong>Correcta:</strong>
  <%= @pregunta.correcta %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @pregunta.estado %>
</p>

<%= link_to 'Edit', edit_pregunta_path(@pregunta) %> |
<%= link_to 'Back', preguntas_path %>