config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  get 'examen', to: 'examen#index'
  get 'examen/:codigo', to: 'examen#show', as: 'examen_codigo'
  root to: 'home#inicio', as: 'inicio'
  resources :preguntas
  resources :evaluaciones

  devise_for :users     #metodos API REST para la APP de pasajes

	scope 'api' do
	  scope 'v1' do
  		resources :respuestas
  		#resources :empresas
  		#resources :imagenes
  		resources :roles
	  end
	end
end

app/models/respuesta.rb
# == Schema Information
#
# Table name: respuestas
#
#  id         :integer          not null, primary key
#  nombre     :string
#  pregunta1  :integer
#  pregunta2  :integer
#  pregunta3  :integer
#  pregunta4  :integer
#  pregunta5  :integer
#  codigo     :string
#  nota       :integer
#  estado     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Respuesta < ApplicationRecord

	validates :codigo, uniqueness: true

	validates :nombre, :pregunta1, :pregunta2, :pregunta3, :pregunta4, :pregunta5, presence: true

	before_create :create_record

	private
	def create_record
		self.estado = "completado"
		self.codigo = ([nil]*8).map { ((48..57).to_a+(65..90).to_a+(97..122).to_a).sample.chr }.join
	end
end

app/controllers/respuestas_controller.rb
class RespuestasController < ActionController::Base
  layout "index"
  before_action :set_respuesta, only: [:show, :edit, :update, :destroy]

  # GET /respuestas
  def index
    @respuestas = Respuesta.all

    respond_to do |format|
      format.html
      format.json { render json: @respuestas }
    end
  end

  # GET /respuestas/1
  def show

    respond_to do |format|
      format.html
      format.json { render json: @respuesta }
    end

  end

  # GET /respuestas/new
  def new
    @respuesta = Respuesta.new
  end

  # GET /respuestas/1/edit
  def edit
  end

  # POST /respuestas
  def create
    @respuesta = Respuesta.new(respuesta_params)

    if @respuesta.save
      render json: @respuesta, status: :created, location: @respuesta
    else
      render json: @respuesta.errors, status: :unprocessable_entity
    end

    #if @respuesta.save
    #  redirect_to @respuesta, notice: 'Respuesta was successfully created.'
    #else
    #  render :new
    #end
  end

  # PATCH/PUT /respuestas/1
  def update
    if @respuesta.update(empresa_params)
      render json: @respuesta
    else
      render json: @respuesta.errors, status: :unprocessable_entity
    end
  end

  # DELETE /respuestas/1
  def destroy
    @respuesta.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_respuesta
      @respuesta = Respuesta.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def respuesta_params
      params.require(:respuesta).permit(:nombre, :pregunta1, :pregunta2, :pregunta3, :pregunta4, :pregunta5, :codigo, :nota, :estado)
    end
end

app/helpers/respuestas_helper.rb
module RespuestasHelper
end

app/views/respuestas/_form.html.erb
<%= form_with(model: respuesta) do |form| %>
  <% if respuesta.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(respuesta.errors.count, "error") %> prohibited this respuesta from being saved:</h2>

      <ul>
        <% respuesta.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :pregunta1 %>
    <%= form.number_field :pregunta1 %>
  </div>

  <div class="field">
    <%= form.label :pregunta2 %>
    <%= form.number_field :pregunta2 %>
  </div>

  <div class="field">
    <%= form.label :pregunta3 %>
    <%= form.number_field :pregunta3 %>
  </div>

  <div class="field">
    <%= form.label :pregunta4 %>
    <%= form.number_field :pregunta4 %>
  </div>

  <div class="field">
    <%= form.label :pregunta5 %>
    <%= form.number_field :pregunta5 %>
  </div>

  <div class="field">
    <%= form.label :codigo %>
    <%= form.text_field :codigo %>
  </div>

  <div class="field">
    <%= form.label :nota %>
    <%= form.number_field :nota %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.text_field :estado %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/respuestas/edit.html.erb
<h1>Editing Respuesta</h1>

<%= render 'form', respuesta: @respuesta %>

<%= link_to 'Show', @respuesta %> |
<%= link_to 'Back', respuestas_path %>

app/views/respuestas/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Inicio', inicio_path %>
<h1>Respuestas</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Pregunta1</th>
      <th>Pregunta2</th>
      <th>Pregunta3</th>
      <th>Pregunta4</th>
      <th>Pregunta5</th>
      <th>Codigo</th>
      <th>Nota</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @respuestas.each do |respuesta| %>
      <tr>
        <td><%= respuesta.nombre %></td>
        <td><%= respuesta.pregunta1 %></td>
        <td><%= respuesta.pregunta2 %></td>
        <td><%= respuesta.pregunta3 %></td>
        <td><%= respuesta.pregunta4 %></td>
        <td><%= respuesta.pregunta5 %></td>
        

        <td><%= link_to respuesta.codigo, examen_codigo_path(respuesta.codigo) %></td>

        <td><%= respuesta.nota %></td>
        <td><%= respuesta.estado %></td>
        <td><%#= link_to 'Show', respuesta %></td>
        <td><%#= link_to 'Edit', edit_respuesta_path(respuesta) %></td>
        <td><%#= link_to 'Destroy', respuesta, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/respuestas/new.html.erb
<h1>New Respuesta</h1>

<%= render 'form', respuesta: @respuesta %>

<%= link_to 'Back', respuestas_path %>

app/views/respuestas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @respuesta.nombre %>
</p>

<p>
  <strong>Pregunta1:</strong>
  <%= @respuesta.pregunta1 %>
</p>

<p>
  <strong>Pregunta2:</strong>
  <%= @respuesta.pregunta2 %>
</p>

<p>
  <strong>Pregunta3:</strong>
  <%= @respuesta.pregunta3 %>
</p>

<p>
  <strong>Pregunta4:</strong>
  <%= @respuesta.pregunta4 %>
</p>

<p>
  <strong>Pregunta5:</strong>
  <%= @respuesta.pregunta5 %>
</p>

<p>
  <strong>Codigo:</strong>
  <%= @respuesta.codigo %>
</p>

<p>
  <strong>Nota:</strong>
  <%= @respuesta.nota %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @respuesta.estado %>
</p>

<%= link_to 'Edit', edit_respuesta_path(@respuesta) %> |
<%= link_to 'Back', respuestas_path %>